# Generated by Django 5.2.13 on 2026-04-19 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_create_default_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key_rotation_days',
            field=models.IntegerField(default=90, help_text='Rotate API keys (days)'),
        ),
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark theme'),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_2fa',
            field=models.BooleanField(default=False, help_text='Require 2FA for all logins'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_whitelist_enabled',
            field=models.BooleanField(default=False, help_text='Only allow logins from approved IPs'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_notifications',
            field=models.BooleanField(default=True, help_text='Get alerts when someone logs in'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_expiry_days',
            field=models.IntegerField(default=90, help_text='Require password change (days)'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30, help_text='Auto-logout after inactivity (minutes)'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspicious_login_alerts',
            field=models.BooleanField(default=True, help_text='Alert on logins from new locations'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('secret', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='authenticat_user_id_297b16_idx'), models.Index(fields=['key'], name='authenticat_key_bb02b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'unique_together': {('user', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('login_suspicious', 'Suspicious Login'), ('password_changed', 'Password Changed'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('session_terminated', 'Session Terminated'), ('ip_whitelisted', 'IP Whitelisted'), ('settings_changed', 'Settings Changed'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='authenticat_user_id_63e710_idx'), models.Index(fields=['event_type', '-timestamp'], name='authenticat_event_t_c168af_idx'), models.Index(fields=['-timestamp'], name='authenticat_timesta_4fee9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='authenticat_user_id_a8ffe0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='authenticat_user_id_f427c8_idx'), models.Index(fields=['-last_activity'], name='authenticat_last_ac_44c1b2_idx')],
            },
        ),
    ]
