# Generated by Django 5.2.13 on 2026-05-01 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_api_key_rotation_days_user_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='attempted_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
