# Generated by Django 5.2.13 on 2026-04-19 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('certificate_type', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('serial_number', models.CharField(db_index=True, max_length=128)),
                ('signature_algorithm', models.CharField(max_length=128)),
                ('key_length', models.PositiveIntegerField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('days_remaining', models.IntegerField(default=0)),
                ('risk_level', models.CharField(max_length=50)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(default='agent', max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['valid_to'],
            },
        ),
    ]
