# Generated by Django 5.2.13 on 2026-04-19 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='agent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='thumbprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='source_type',
            field=models.CharField(default='scanner', max_length=50),
        ),
        migrations.CreateModel(
            name='CertificateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('agent_name', models.CharField(help_text='Human-readable agent name', max_length=255)),
                ('agent_type', models.CharField(choices=[('powershell', 'PowerShell Script'), ('manual', 'Manual Upload'), ('api', 'Direct API')], default='powershell', max_length=50)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_id', 'is_active'], name='certificate_agent_i_0c8dbc_idx'), models.Index(fields=['token', 'is_active'], name='certificate_token_b96619_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('unauthorized', 'Unauthorized'), ('malformed', 'Malformed Payload')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('certificates_submitted', models.PositiveIntegerField(default=0)),
                ('certificates_created', models.PositiveIntegerField(default=0)),
                ('certificates_updated', models.PositiveIntegerField(default=0)),
                ('certificates_failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='certificates.certificateagent')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', '-timestamp'], name='certificate_agent_i_9f7ce3_idx'), models.Index(fields=['status', '-timestamp'], name='certificate_status_5583f2_idx')],
            },
        ),
    ]
