# Generated by Django 5.2.13 on 2026-04-19 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_agent_id_certificate_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_chain',
            field=models.JSONField(blank=True, default=list, help_text='List of intermediate/root cert data'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='last_verified',
            field=models.DateTimeField(blank=True, help_text='Last validation timestamp', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='source_priority',
            field=models.IntegerField(default=0, help_text='Priority for deduplication: 100=internal, 50=scanner'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_length',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='risk_level',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='source_type',
            field=models.CharField(db_index=True, default='scanner', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['domain', 'source_type'], name='certificate_domain_209d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['valid_to', 'status'], name='certificate_valid_t_d05e92_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['risk_level', 'source_type'], name='certificate_risk_le_21cc2a_idx'),
        ),
    ]
