# Generated by Django 5.2.13 on 2026-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_certificate_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='risk_reasoning',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of risk calculation (for audit trail)'),
        ),
    ]
