# Generated by Django 5.2.13 on 2026-04-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_adcs_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adcscertificate',
            new_name='certificate_source__b02e7f_idx',
            old_name='certificates_source_tem_idx',
        ),
        migrations.RenameIndex(
            model_name='adcscertificate',
            new_name='certificate_request_4b7240_idx',
            old_name='certificates_request_idx',
        ),
        migrations.RenameIndex(
            model_name='adcsconnectiontest',
            new_name='certificate_source__fb91da_idx',
            old_name='certificates_source_cre_idx',
        ),
        migrations.RenameIndex(
            model_name='adcscredentialhistory',
            new_name='certificate_source__b82812_idx',
            old_name='certificates_source_cha_idx',
        ),
        migrations.RenameIndex(
            model_name='adcssource',
            new_name='certificate_is_acti_3bdd2b_idx',
            old_name='certificates_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='adcssource',
            new_name='certificate_connect_b44dda_idx',
            old_name='certificates_connect_idx',
        ),
        migrations.RenameIndex(
            model_name='adcssource',
            new_name='certificate_last_sy_07afc7_idx',
            old_name='certificates_last_sy_idx',
        ),
        migrations.RenameIndex(
            model_name='adcssynchistory',
            new_name='certificate_source__9916c9_idx',
            old_name='certificates_source_sta_idx',
        ),
        migrations.RenameIndex(
            model_name='adcssynchistory',
            new_name='certificate_status_5c396c_idx',
            old_name='certificates_status_idx',
        ),
        migrations.AddField(
            model_name='certificate',
            name='crypto_findings',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed cryptographic analysis (algorithm strength, key analysis)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_self_signed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether certificate is self-signed'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='san_list',
            field=models.JSONField(blank=True, default=list, help_text='List of Subject Alternative Names'),
        ),
        migrations.AlterField(
            model_name='adcssynchistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
