# Generated by Django 5.2.13 on 2026-05-01 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_rename_certificates_source_tem_idx_certificate_source__b02e7f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DomainScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(blank=True, default='', max_length=50)),
                ('risk_reasoning', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_scan_history', to='certificates.certificate')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='certificates.domain')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['domain', '-scanned_at'], name='certificate_domain__d7b045_idx'), models.Index(fields=['status', '-scanned_at'], name='certificate_status_6f0d19_idx')],
            },
        ),
    ]
