# Generated by Django 5.2.13 on 2026-04-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_rename_metadata_to_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='alertauditlog',
            new_name='audit_logs__user_id_43b6c4_idx',
            old_name='audit_logs__user_id_a_idx',
        ),
        migrations.RenameIndex(
            model_name='alertauditlog',
            new_name='audit_logs__action_b60ca9_idx',
            old_name='audit_logs__action_a_idx',
        ),
        migrations.RenameIndex(
            model_name='alertauditlog',
            new_name='audit_logs__alert_i_7680e0_idx',
            old_name='audit_logs__alert_id_idx',
        ),
        migrations.RenameIndex(
            model_name='alertauditlog',
            new_name='audit_logs__certifi_efa916_idx',
            old_name='audit_logs__cert_id_a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__user_id_d31e2a_idx',
            old_name='audit_logs__user_id_c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__action_70fdcf_idx',
            old_name='audit_logs__action_c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__target__f5f9c7_idx',
            old_name='audit_logs__target__idx',
        ),
        migrations.RenameIndex(
            model_name='certificateauditlog',
            new_name='audit_logs__user_id_fe1bb2_idx',
            old_name='audit_logs__user_id_t_idx',
        ),
        migrations.RenameIndex(
            model_name='certificateauditlog',
            new_name='audit_logs__action_2f23a7_idx',
            old_name='audit_logs__action_t_idx',
        ),
        migrations.RenameIndex(
            model_name='certificateauditlog',
            new_name='audit_logs__certifi_01235c_idx',
            old_name='audit_logs__cert_id_idx',
        ),
    ]
