# Generated by Django 5.2.13 on 2026-04-19 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When alert was acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.CharField(blank=True, help_text='Username who acknowledged the alert', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('EXPIRY', 'Certificate Expiry'), ('CRYPTO_WEAKNESS', 'Cryptographic Weakness'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='certificate_domain',
            field=models.CharField(blank=True, db_index=True, help_text='Associated Certificate Domain', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='certificate_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Associated Certificate ID', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_acknowledged',
            field=models.BooleanField(default=False, help_text='Whether alert has been acknowledged by admin'),
        ),
        migrations.AddField(
            model_name='alert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'created_at'], name='alerts_aler_severit_29c5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'certificate_domain'], name='alerts_aler_alert_t_4fac4a_idx'),
        ),
    ]
