# Generated by Django 5.2.13 on 2026-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_options_alert_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='threshold_days',
            field=models.IntegerField(blank=True, help_text='Expiry threshold that triggered alert', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_source',
            field=models.CharField(blank=True, default='scheduled', help_text='scheduled or immediate', max_length=50),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['dedupe_key', 'created_at'], name='alerts_aler_dedupe__f07633_idx'),
        ),
    ]
