# Generated by Django 5.2.13 on 2026-04-19 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_expiry_days', models.PositiveIntegerField(default=7, help_text='Days until expiry to mark as CRITICAL (default: 7)')),
                ('high_expiry_days', models.PositiveIntegerField(default=30, help_text='Days until expiry to mark as HIGH (default: 30)')),
                ('medium_expiry_days', models.PositiveIntegerField(default=90, help_text='Days until expiry to mark as MEDIUM (default: 90)')),
                ('weak_key_bits', models.PositiveIntegerField(default=2048, help_text='Key length below this is weak (default: 2048)')),
                ('medium_key_bits', models.PositiveIntegerField(default=3072, help_text='Key length below this is moderate (default: 3072)')),
                ('self_signed_penalty', models.PositiveIntegerField(default=25, help_text='Points to add for self-signed certificates (default: 25)')),
                ('weak_algorithm_penalty', models.PositiveIntegerField(default=20, help_text='Points to add for weak algorithms like MD5/SHA1 (default: 20)')),
                ('critical_threshold', models.PositiveIntegerField(default=75, help_text='Risk score threshold for CRITICAL level (default: 75)')),
                ('high_threshold', models.PositiveIntegerField(default=50, help_text='Risk score threshold for HIGH level (default: 50)')),
                ('medium_threshold', models.PositiveIntegerField(default=25, help_text='Risk score threshold for MEDIUM level (default: 25)')),
                ('last_modified_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last modification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='Last superadmin who modified these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risk Configuration',
                'verbose_name_plural': 'Risk Configurations',
            },
        ),
    ]
